SingleNode:
  restart: always
  image: redis:5.0.0
  ports:
    - "6379:6379"
  environment:
    - DEBUG=false

RedisCluster:
  restart: always
  image: m0stwanted/redis-cluster:latest
  ports:
    - "30001:30001"
    - "30002:30002"
    - "30003:30003"
    - "30004:30004"
    - "30005:30005"
    - "30006:30006"
  environment:
    - DEBUG=false
