name: Microsite
on:
  push:
    branches:
      - master
    paths:
      - "site/**"
      - "**/README.md"

jobs:
  publish:
    env:
      GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    runs-on: ubuntu-18.04
    steps:
      - uses: "actions/checkout@v2.1.0"
      - uses: "cachix/install-nix-action@v12"
      - uses: "cachix/cachix-action@v8"
        with:
          name: scala-microsite
          signingKey: "${{ secrets.CACHIX_SIGNING_KEY }}"
      - name: "Building microsite 🚧"
        run: nix-shell --run "sbt publishSite"
