name: Microsite
on:
  push:
    branches:
      - master
    paths:
      - "site/**"
      - "**/README.md"

jobs:
  publish:
    env:
      GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.2
        with:
          fetch-depth: 0 # fetch all branches & tags

      - name: "Install Nix ❄️"
        uses: cachix/install-nix-action@v12
        with:
          skip_adding_nixpkgs_channel: true

      - name: "Install Cachix ❄️"
        uses: cachix/cachix-action@v8
        with:
          name: redis4cats
          signingKey: "${{ secrets.CACHIX_SIGNING_KEY }}"

      - name: "Building microsite 🚧"
        run: nix-shell --run "sbt publishSite"
